/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectquanlysinhvien;
import projectquanlysinhvien2.*;

/**
 *
 * @author Admin
 */
public class FrmCuaSoChinh extends javax.swing.JFrame {
    private static int userId = -1;
    private static String tenDangNhap = "";
    private static String hoTen = "";

    public static int getUserId() {
        return userId;
    }

    public static void setUserId(int userId) {
        FrmCuaSoChinh.userId = userId;
    }

    public static String getTenDangNhap() {
        return tenDangNhap;
    }
    public static void setTenDangNhap(String tenDangNhap) {
        FrmCuaSoChinh.tenDangNhap = tenDangNhap;
    }

    public static String getHoTen() {
        return hoTen;
    }

    public static void setHoTen(String hoTen) {
        FrmCuaSoChinh.hoTen = hoTen;
    }
    
    public boolean isDangNhap = false;
    /**
     * Creates new form FrmCuaSoChinh
     */
    public FrmCuaSoChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHeThong = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        menuItemDanhSach = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuNghiepVu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuTroGiup = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenuHeThong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jMenuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/settings_16.png"))); // NOI18N
        jMenuHeThong.setText(" Hệ thống");
        jMenuHeThong.setToolTipText("");
        jMenuHeThong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuHeThong.add(jSeparator1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Images/007.png"))); // NOI18N
        jMenu1.setText("Thông tin người dùng");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuItemDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItemDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/List_BulletsHS.png"))); // NOI18N
        menuItemDanhSach.setText("Danh sách");
        menuItemDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDanhSachActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemDanhSach);

        jMenuHeThong.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/user.png"))); // NOI18N
        jMenu2.setText("Thông tin sinh viên");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/List_BulletsHS.png"))); // NOI18N
        jMenuItem1.setText("Danh Sách");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuHeThong.add(jMenu2);

        jMenuBar1.add(jMenuHeThong);

        jMenuNghiepVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/edoc_register.gif"))); // NOI18N
        jMenuNghiepVu.setText("Nghiệp vụ");
        jMenuNghiepVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setText("Tra cứu điểm thi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuNghiepVu.add(jMenuItem3);

        jMenuBar1.add(jMenuNghiepVu);

        jMenuTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/Help.png"))); // NOI18N
        jMenuTroGiup.setText("Trợ giúp");
        jMenuTroGiup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("CHƯƠNG TRÌNH QUẢN LÝ SINH VIÊN");
        this.setExtendedState(MAXIMIZED_BOTH);
       
    }//GEN-LAST:event_formWindowOpened
    
    //Kieemr tra quyền(boolean quyen){
    public void kiemTraQuyen(boolean isQuyen){
        
    }
    private void menuItemDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDanhSachActionPerformed
        FrmDanhSachNguoiDung ds = new FrmDanhSachNguoiDung();
        
        ds.setVisible(true);
    }//GEN-LAST:event_menuItemDanhSachActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      FrmHienThiDanhSachSinhVien hienThi = new FrmHienThiDanhSachSinhVien();
      
      hienThi.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmTraCuuDiemThi traCuuDiem = new FrmTraCuuDiemThi();
        
        traCuuDiem.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuaSoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHeThong;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuNghiepVu;
    private javax.swing.JMenu jMenuTroGiup;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuItemDanhSach;
    // End of variables declaration//GEN-END:variables
}
