/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectquanlysinhvien;

import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import projectquanlysinhvien2.*;

/**
 *
 * @author Admin
 */
public class FrmThemMoi extends javax.swing.JFrame {
    public String sinhVienId = "";

    public String getSinhVienId() {
        return sinhVienId;
    }

    public void setSinhVienId(String sinhVienId) {
        this.sinhVienId = sinhVienId;
    }
        
    /**
     * Creates new form FrmThemMoi
     */
    public FrmThemMoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        cboMonHoc = new javax.swing.JComboBox<>();
        cboPhongThi = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtDiemThi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnDong = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        cboIdSV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Sinh viên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Môn học");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Phòng thi:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày thi:");

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPhongThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboPhongThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Điểm Thi:");

        txtDiemThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/cancel.gif"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/Update.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        cboIdSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboIdSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboIdSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIdSVActionPerformed(evt);
            }
        });
        cboIdSV.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboIdSVPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboIdSV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoTen))
                            .addComponent(cboMonHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPhongThi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiemThi, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboIdSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(btnCapNhat))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        //Khai báo đối tượng
        DiemThiBusiness diemThiBus = new DiemThiBusiness();
        DiemThi objDiemThi = new DiemThi();
        //Khai báo biến
        String maId = "", hoTen = "", strDiemThi = "", monHocId = "", phongHocId = "";
        double diemThi = 0;
        Date ngayThi;     
        //Lấy dữ liệu từ giao diện
        ngayThi = jDateChooser1.getDate();
        hoTen = txtHoTen.getText();
        strDiemThi = txtDiemThi.getText();
        
        //Lấy Id môn học
        MonHoc objMonHoc = (MonHoc) cboMonHoc.getSelectedItem();
        monHocId = objMonHoc.getId();
        
        //Lấy Id phòng
        PhongHoc objPhongHoc = (PhongHoc) cboPhongThi.getSelectedItem();
        phongHocId = objPhongHoc.getId();
        
        //Lấy Id sinh viên
        IDSinhVien objIdSinhVien = (IDSinhVien) cboIdSV.getSelectedItem();
        maId = objIdSinhVien.getId();
        
        if (hoTen.length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Bạn cần phải nhập họ tên");
            txtHoTen.requestFocus();
            return;
        }
        if (strDiemThi.length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Bạn cần phải nhập điểm thi");
            txtDiemThi.requestFocus();
            return;
        }
        diemThi = Double.parseDouble(strDiemThi);
        
        //Truyền dữ liệu vào đối tượng
        objDiemThi.setSinhVienId(maId);
        objDiemThi.setHoTen(hoTen);
        objDiemThi.setDiemThi(diemThi);
        objDiemThi.setNgayThi(ngayThi);
        objDiemThi.setMonHocId(monHocId);
        objDiemThi.setPhongHocId(phongHocId);
        
        boolean kq = false;
        if (!sinhVienId.isEmpty()) {
            kq = diemThiBus.capNhat(objDiemThi);
            
        } else {
            //Gọi hàm thêm mới
            kq = diemThiBus.themMoi(objDiemThi);
        }
        if (kq) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
        } 
        
        //Reload lại danh sách
        FrmTraCuuDiemThi.hienThiDanhSachDiem();
     
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        hienThiDanhSachId();
        hienThiDanhSachMonHoc();
        hienThiDanhSachPhongHoc();
        //TH sửa
        if (!sinhVienId.isEmpty()) {
            this.setTitle("Sửa điểm thi sinh viên");
            hienThiChiTietDiemThi();
            
        } else {
            this.setTitle("Thêm mới thông tin sinh viên ");
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void cboIdSVPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboIdSVPropertyChange
      
    }//GEN-LAST:event_cboIdSVPropertyChange

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed

    private void cboIdSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIdSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboIdSVActionPerformed

    private void hienThiChiTietDiemThi() {
        //Khai báo một đối tượng 
        DiemThiBusiness diemThiBus = new DiemThiBusiness();
        
        DiemThi objDiemThi = diemThiBus.layChiTietTheoMa(sinhVienId);

        //Hiển thị lên frm
        txtHoTen.setText(objDiemThi.getHoTen());
        txtDiemThi.setText(objDiemThi.getDiemThi() + "");
        jDateChooser1.setDate(objDiemThi.getNgayThi());
        
        //Xử lý chọn Combo box của sinh viên trong danh sách hiển thị lên combobox
        if (!objDiemThi.getSinhVienId().isEmpty()) {
            IDSinhVienBusiness IdBus = new IDSinhVienBusiness();
            
            IDSinhVien objID = IdBus.layChiTietTheoMa(objDiemThi.getSinhVienId());
            if (objID != null) {
                cboIdSV.getModel().setSelectedItem(objID);
            }
        }    
            //Xử lý chọn môn học
            if (!objDiemThi.getMonHocId().isEmpty()){
            MonHocBusiness monHocBus = new MonHocBusiness();     
            
            MonHoc objMonHoc = monHocBus.layChiTietTheoMa(objDiemThi.getMonHocId());
            if (objMonHoc != null) {
                cboMonHoc.getModel().setSelectedItem(objMonHoc);
            }
            }
            
            if (!objDiemThi.getPhongHocId().isEmpty()){
            //xử lý phòng học
            PhongHocBusiness phongHocBus = new PhongHocBusiness();
            
            PhongHoc objPhongHoc = phongHocBus.layChiTietTheoMa(objDiemThi.getPhongHocId());
            if (objPhongHoc != null) {
                cboPhongThi.getModel().setSelectedItem(objPhongHoc);
            }   
    }
    }      
    private void hienThiDanhSachMonHoc() {
        ///Khai báo 1 đối tượng
        MonHocBusiness monHocBus = new MonHocBusiness();
        //Lấy danh sách khoa
        List<MonHoc> lstMonHoc = monHocBus.layDanhSachMonHoc();
        MonHoc root = new MonHoc();
        root.setMaMH("");
        root.setTenMonHoc("---Chọn môn---");
        lstMonHoc.add(0, root);
        //Khai báo 1 đối tượng để hiển thị thông tin lên combobox
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //Duyệt để đưa vào danh sách
        for(MonHoc o: lstMonHoc)
        {
            model.addElement(o);
        }
        //Hiển thị lên combobox
        cboMonHoc.setModel(model);
        //Tuỳ biến lại từng item của combobox
        cboMonHoc.setRenderer(new MonHocRender());
    }
    
    //Hàm hiển thị danh sách phòng học
    private void hienThiDanhSachPhongHoc() {
        ///Khai báo 1 đối tượng
        PhongHocBusiness phongHocBus = new PhongHocBusiness();
        //Lấy danh sách khoa
        List<PhongHoc> lstPhongHoc = phongHocBus.layDanhSachPhongThi();
        PhongHoc root = new PhongHoc();
        root.setMaPhong("");
        root.setTenPhong("---Chọn phòng---");
        lstPhongHoc.add(0, root);
        //Khai báo 1 đối tượng để hiển thị thông tin lên combobox
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //Duyệt để đưa vào danh sách
        for(PhongHoc o: lstPhongHoc)
        {
            model.addElement(o);
        }
        //Hiển thị lên combobox
        cboPhongThi.setModel(model);
        //Tuỳ biến lại từng item của combobox
        cboPhongThi.setRenderer(new PhongHocRender());
    }
    
    //Hiển thị danh sách Id
    private void hienThiDanhSachId() {
        ///Khai báo 1 đối tượng
        IDSinhVienBusiness IdBus = new IDSinhVienBusiness();
        //Lấy danh sách khoa
        List<IDSinhVien> lstId = IdBus.layDanhSachIdSinhVien();
        IDSinhVien root = new IDSinhVien();
        root.setId("---Chọn ID---");
        lstId.add(0, root);
        //Khai báo 1 đối tượng để hiển thị thông tin lên combobox
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //Duyệt để đưa vào danh sách
        for(IDSinhVien o: lstId)
        {
            model.addElement(o);
        }
        //Hiển thị lên combobox
        cboIdSV.setModel(model);
        //Tuỳ biến lại từng item của combobox
        cboIdSV.setRenderer(new IDSinhVienRender());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmThemMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmThemMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmThemMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmThemMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmThemMoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDong;
    private static javax.swing.JComboBox<String> cboIdSV;
    private static javax.swing.JComboBox<String> cboMonHoc;
    private static javax.swing.JComboBox<String> cboPhongThi;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDiemThi;
    private javax.swing.JTextField txtHoTen;
    // End of variables declaration//GEN-END:variables
}
