/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectquanlysinhvien2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projectquanlysinhvien.nguoiDung;
import projectquanlysinhvien.nguoiDungBusiness;

/**
 *
 * @author Admin
 */
public class FrmHienThiDanhSachSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form FrmHienThiDanhSachSinhVien
     */
    public FrmHienThiDanhSachSinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKhoa = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDanhSach = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnLocSinhVien = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("DANH SÁCH SINH VIÊN");

        jScrollPane1.setViewportView(jListKhoa);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDanhSach);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("KHOA");

        btnLocSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLocSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/User 7 Check.png"))); // NOI18N
        btnLocSinhVien.setText("Lọc sinh viên");
        btnLocSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocSinhVienActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/EditTableHS.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/103.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectquanlysinhvien/image/Images/Images/cancel.gif"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnDong))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(btnLocSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(316, 316, 316))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocSinhVien))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        hienThiDanhSachKhoa();
        hienThiDanhSachSinhVien();
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    FrmCapNhat capNhat = new FrmCapNhat();
    
    capNhat.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int dongChon = 0;
        String maSinhVien = "";
        dongChon = jTableDanhSach.getSelectedRow();
        maSinhVien = "" + jTableDanhSach.getValueAt(dongChon, 1);
        FrmCapNhat sua = new FrmCapNhat();
        //Truyền lên giao diện
        sua.setMaSinhVien(maSinhVien);
        sua.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        //Xóa thông tin
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa thông tin này không?",
                "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //Nếu đúng muốn xóa
        if (ketQua == JOptionPane.YES_OPTION) {
            String maSV = "";
            int dongChon = 0;
            //Lấy dòng chọn
            dongChon = jTableDanhSach.getSelectedRow();
            maSV = "" + jTableDanhSach.getValueAt(dongChon, 1);
            //Khai báo đối tượng
            SinhVienBusiness sinhVienBus = new SinhVienBusiness();
            //Gọi hàm xóa
            boolean kq = sinhVienBus.xoaSinhVien(maSV);
            hienThiDanhSachSinhVien();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLocSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocSinhVienActionPerformed
        if (jListKhoa.getSelectedIndex() != -1){         
        //Khai báo List
            List<ChuyenKhoa> lstCk = new ArrayList<ChuyenKhoa>();
            lstCk = jListKhoa.getSelectedValuesList();
            locSinhVienTheoKhoa(lstCk);       
        } else {
            hienThiDanhSachSinhVien();          
        }
    }//GEN-LAST:event_btnLocSinhVienActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed
    
    public static void locSinhVienTheoKhoa(List<ChuyenKhoa> lstCk) {
        //Khai báo cột tiêu đề
        String[] cotTieuDe = new String[]{"ID", "Mã SV", "Họ Tên", "Giới Tính", "Ngày Sinh", "Điện Thoại" , "Email"
        , "Địa Chỉ", "Chuyên Khoa ID"};
        //Khai báo model
        DefaultTableModel model = new DefaultTableModel(cotTieuDe, 0);
        //Khai báo đối tượng để gọi hàm hiển thị danh sách
        SinhVienBusiness sinhVienBus = new SinhVienBusiness();
        //Gọi hàm hiển thị danh sách
        List<SinhVien> lstSinhVien = sinhVienBus.timKiemSinhVien(lstCk);

        Object row[];
        for (SinhVien sv : lstSinhVien) {
            row = new Object[9];
            row[0] = sv.getId();
            row[1] = sv.getMaSV();
            row[2] = sv.getHoTen();
            row[3] = sv.getGioiTinh();
            row[4] = sv.getNgaySinh();
            row[5] = sv.getDienThoai();
            row[6] = sv.getEmail();
            row[7] = sv.getDiaChi();
            row[8] = sv.getChuyenKhoaId();

            model.addRow(row);
        }
        jTableDanhSach.setModel(model);
    }
    public static void hienThiDanhSachSinhVien() {
        //Khai báo cột tiêu đề
        String[] cotTieuDe = new String[]{"ID", "Mã SV", "Họ Tên", "Giới Tính", "Ngày Sinh", "Điện Thoại" , "Email"
        , "Địa Chỉ", "Chuyên Khoa ID"};
        //Khai báo model
        DefaultTableModel model = new DefaultTableModel(cotTieuDe, 0);
        //Khai báo đối tượng để gọi hàm hiển thị danh sách
        SinhVienBusiness sinhVienBus = new SinhVienBusiness();
        //Gọi hàm hiển thị danh sách
        List<SinhVien> lstSinhVien = sinhVienBus.layDanhSachSinhVien();

        Object row[];
        for (SinhVien sv : lstSinhVien) {
            row = new Object[9];
            row[0] = sv.getId();
            row[1] = sv.getMaSV();
            row[2] = sv.getHoTen();
            row[3] = sv.getGioiTinh();
            row[4] = sv.getNgaySinh();
            row[5] = sv.getDienThoai();
            row[6] = sv.getEmail();
            row[7] = sv.getDiaChi();
            row[8] = sv.getChuyenKhoaId();

            model.addRow(row);
        }
        jTableDanhSach.setModel(model);
    }
    
    //Hiển thị khoa lên JList
    public static void hienThiDanhSachKhoa(){
        ChuyenKhoaBusiness chuyenKhoaBus = new ChuyenKhoaBusiness();
        //Lấy danh sách khoa
        List<ChuyenKhoa> lstChuyenKhoa = chuyenKhoaBus.layDanhSachChuyenKhoa();
        //Khai báo model để truyền lên jList
        DefaultListModel model = new DefaultListModel();
        
        //Duyệt list để truyền vào model
        for (ChuyenKhoa o : lstChuyenKhoa) {
            model.addElement(o);         
        }
        //Hiển thị lên jList
        jListKhoa.setModel(model);
        //Tùy biến lại từng item của jList
        jListKhoa.setCellRenderer(new KhoaRenderJlist());
    }
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHienThiDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHienThiDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHienThiDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHienThiDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHienThiDanhSachSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLocSinhVien;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JList<ChuyenKhoa> jListKhoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTableDanhSach;
    // End of variables declaration//GEN-END:variables
}
